config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "welcome#index"

  resources :managers

  resources :guests, :except => [:destroy, :new] do
    resources :invitations, :except => [:edit, :new, :create]
  end

  resources :restaurants do
    resources :configurations, :only => [:create] do
      post :setup_seats
      resources :seats, :only => [:show]
    end

    resources :reservations, :except => [:destroy]

    resources :menus, :except => [:index] do
      resources :meals, :except => [:index]
    end
  end


  resource :users do
    resources :friendships, :except => [:edit, :update, :new]

    resources :reviews, :only => [:index, :show, :update]
  end
end

app/models/admin.rb
class Admin < User
  before_create :set_role

  default_scope { where(:role => "admin") }

  private

  def set_role
    self.role ||= "admin"
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  belongs_to :guest, :foreign_key => :user_id

  validates_presence_of :user_id
  validates_presence_of :friend_id

  def friend
    Guest.find(self.friend_id)
  end

end

app/models/guest.rb
class Guest < User
  before_create :set_role

  default_scope { where(:role => "guest") }

  private

  def set_role
    self.role ||= "guest"
  end

  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR full_name ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base

  belongs_to :user, -> { where(:role => "guest") }
  belongs_to :reservation

  has_one :review, :dependent => :destroy

  delegate :date, :to => :reservation
  delegate :duration, :to => :reservation
  delegate :restaurant, :to => :reservation

  delegate :first_name, :to => :user
  delegate :last_name, :to => :user

  def expired?
    date_range = self.date.localtime..self.date.localtime + self.duration.hours

    unless date_range.cover?(Time.now)
      unless self.review.present?
        if self.confirmed
          self.create_review!(:restaurant_id => self.restaurant.id,
                              :user_id => self.user.id)
        end
      end
    end

    !date_range.cover?(Time.now)
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_mappable :default_units => :kilometers,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
end

app/models/manager.rb
class Manager < User
  before_create :set_role

  default_scope { where(:role => "manager") }

  private

  def set_role
    self.role ||= "manager"
  end
end

app/models/meal.rb
class Meal < ActiveRecord::Base

  belongs_to :menu

  validates_presence_of :title
  validates_presence_of :price

end

app/models/menu.rb
class Menu < ActiveRecord::Base

  belongs_to :restaurant

  has_many :meals

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  has_and_belongs_to_many :seats
  has_many :invitations
  has_one :review

  belongs_to :restaurant
  belongs_to :user

  validates_presence_of :date
  validates_presence_of :duration

  delegate :title, :to => :restaurant

  def expired?
    date_range = self.date.localtime..self.date.localtime + self.duration.hours

    unless date_range.cover?(Time.now)
      unless self.review.present?
        self.create_review!(:restaurant_id => self.restaurant.id,
                            :user_id => self.user.id)
      end
    end

    !date_range.cover?(Time.now)
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  acts_as_mappable :default_units => :meters,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  has_many :managers, -> { where(:role => "manager") }
  has_one :seats_configuration
  has_many :reviews
  has_one :menu

  validates_presence_of :title

  before_create :tap_configuration
  before_create :tap_menu

  def rating
    Review.all.where(:restaurant_id => self.id).average(:rating).to_f
  end

  private

  def tap_configuration
    self.build_seats_configuration
  end

  def tap_menu
    self.build_menu
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :restaurant
  belongs_to :invitation
  belongs_to :reservation

  def reservation
    self[:reservation_id] ? Reservation.find(self[:reservation_id]) : self.invitation.reservation
  end

end

app/models/seat.rb
class Seat < ActiveRecord::Base

  belongs_to :seat_configuration

  has_and_belongs_to_many :reservations

  def reserved?(time)
    return false if self.reservations.empty?

    self.reservations.each do |reservation|
      date_range = reservation.date.localtime..reservation.date.localtime + reservation.duration.hours
      if date_range.cover?(time.to_time)
        return true
      end
    end
    return false
  end

end

app/models/seats_reservation.rb
class SeatsReservation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  acts_as_mappable :default_units => :meters,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  belongs_to :restaurant

  has_many :friendships
  has_many :invitations
  has_many :reservations
  has_many :reviews

  before_create :set_role
  before_save :set_full_name

  def admin?
    self.role == "admin"
  end

  def guest?
    self.role == "guest"
  end

  def manager?
    self.role == "manager"
  end

  def restaurant_manager(restaurant)
    self.restaurant_id == restaurant.id
  end

  def friends_rating(restaurant_id)
    ratings = []

    self.friendships.each do |friendship|
      avg_rating = friendship.friend.reviews.where(:restaurant_id => restaurant_id).average(:rating).to_f
      ratings << avg_rating unless avg_rating == 0
    end

    if ratings.count == 0
      return "Not rated yet"
    else
      rating = ratings.sum / ratings.count
      rating.round(2)
    end
  end

  def friend?(guest)
    !self.friendships.where(:user_id => self.id, :friend_id => guest.id).empty?
  end

  def friendship(friend)
    Friendship.where(:user_id => self.id, :friend_id => friend.id).first
  end

  def common_visits(friend)
    if self.reviews || !self.reviews.empty?
      visits = 0
      self.reviews.each do |review|
        if review.reservation.user.id == friend.id
          visits = visits + 1
        else
          visits = visits + review.reservation.invitations.where(:user_id => friend.id, :confirmed => true).count
        end
      end
      return visits
    else
      return "You haven't been anywhere"
    end
  end

  private

  def set_role
    self.role ||= "guest"
  end

  def set_full_name
    if self.first_name && self.last_name
      self.full_name = "#{self.first_name} #{self.last_name}"
    end
  end

end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: [:show, :edit, :update, :destroy]

  def show
  end

  private
  def set_seat
    @seat = Seat.find(params[:id])
  end

  def seat_params
    params.require(:seat).permit(:x, :y, :reserved, :configuration_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_url(email, size)
      gravatar_id = Digest::MD5::hexdigest(email).downcase
      default_url = "http://www.icon2s.com/img256/256x256-black-white-android-user.png"
      url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=#{CGI::escape(default_url)}?s=#{size}"
  end

end

app/helpers/guests_helper.rb
module GuestsHelper

  def reverse_geocode(guest)
    res = Geokit::Geocoders::GoogleGeocoder.reverse_geocode "#{guest.lat},#{guest.lng}"
    res.full_address
  end

end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x %><br>
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br>
    <%= f.number_field :y %>
  </div>
  <div class="field">
    <%= f.label :reserved %><br>
    <%= f.check_box :reserved %>
  </div>
  <div class="field">
    <%= f.label :configuration_id %><br>
    <%= f.text_field :configuration_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing Seat</h1>

<%= render 'form' %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Seats</h1>

<table>
  <thead>
    <tr>
      <th>X</th>
      <th>Y</th>
      <th>Reserved</th>
      <th>Configuration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seats.each do |seat| %>
      <tr>
        <td><%= seat.x %></td>
        <td><%= seat.y %></td>
        <td><%= seat.reserved %></td>
        <td><%= seat.configuration %></td>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<h1>New Seat</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>X:</strong>
  <%= @seat.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @seat.y %>
</p>

<p>
  <strong>Reserved:</strong>
  <%= @seat.reserved %>
</p>

<p>
  <strong>Configuration:</strong>
  <%= @seat.configuration %>
</p>

<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>