config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "welcome#index"

  resources :managers

  resources :guests, :except => [:destroy, :new] do
    resources :invitations, :except => [:edit, :new, :create]
  end

  resources :restaurants do
    resources :configurations, :only => [:create] do
      post :setup_seats
      resources :seats, :only => [:show]
    end

    resources :reservations, :except => [:destroy]

    resources :menus, :except => [:index] do
      resources :meals, :except => [:index]
    end
  end


  resource :users do
    resources :friendships, :except => [:edit, :update, :new]

    resources :reviews, :only => [:index, :show, :update]
  end
end

app/models/admin.rb
class Admin < User
  before_create :set_role

  default_scope { where(:role => "admin") }

  private

  def set_role
    self.role ||= "admin"
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  belongs_to :guest, :foreign_key => :user_id

  validates_presence_of :user_id
  validates_presence_of :friend_id

  def friend
    Guest.find(self.friend_id)
  end

end

app/models/guest.rb
class Guest < User
  before_create :set_role

  default_scope { where(:role => "guest") }

  private

  def set_role
    self.role ||= "guest"
  end

  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR full_name ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base

  belongs_to :user, -> { where(:role => "guest") }
  belongs_to :reservation

  has_one :review, :dependent => :destroy

  delegate :date, :to => :reservation
  delegate :duration, :to => :reservation
  delegate :restaurant, :to => :reservation

  delegate :first_name, :to => :user
  delegate :last_name, :to => :user

  def expired?
    date_range = self.date.localtime..self.date.localtime + self.duration.hours

    unless date_range.cover?(Time.now)
      unless self.review.present?
        if self.confirmed
          self.create_review!(:restaurant_id => self.restaurant.id,
                              :user_id => self.user.id)
        end
      end
    end

    !date_range.cover?(Time.now)
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_mappable :default_units => :kilometers,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
end

app/models/manager.rb
class Manager < User
  before_create :set_role

  default_scope { where(:role => "manager") }

  private

  def set_role
    self.role ||= "manager"
  end
end

app/models/meal.rb
class Meal < ActiveRecord::Base

  belongs_to :menu

  validates_presence_of :title
  validates_presence_of :price

end

app/models/menu.rb
class Menu < ActiveRecord::Base

  belongs_to :restaurant

  has_many :meals

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  has_and_belongs_to_many :seats
  has_many :invitations
  has_one :review

  belongs_to :restaurant
  belongs_to :user

  validates_presence_of :date
  validates_presence_of :duration

  delegate :title, :to => :restaurant

  def expired?
    date_range = self.date.localtime..self.date.localtime + self.duration.hours

    unless date_range.cover?(Time.now)
      unless self.review.present?
        self.create_review!(:restaurant_id => self.restaurant.id,
                            :user_id => self.user.id)
      end
    end

    !date_range.cover?(Time.now)
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  acts_as_mappable :default_units => :meters,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  has_many :managers, -> { where(:role => "manager") }
  has_one :seats_configuration
  has_many :reviews
  has_one :menu

  validates_presence_of :title

  before_create :tap_configuration
  before_create :tap_menu

  def rating
    Review.all.where(:restaurant_id => self.id).average(:rating).to_f
  end

  private

  def tap_configuration
    self.build_seats_configuration
  end

  def tap_menu
    self.build_menu
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :restaurant
  belongs_to :invitation
  belongs_to :reservation

  def reservation
    self[:reservation_id] ? Reservation.find(self[:reservation_id]) : self.invitation.reservation
  end

end

app/models/seat.rb
class Seat < ActiveRecord::Base

  belongs_to :seat_configuration

  has_and_belongs_to_many :reservations

  def reserved?(time)
    return false if self.reservations.empty?

    self.reservations.each do |reservation|
      date_range = reservation.date.localtime..reservation.date.localtime + reservation.duration.hours
      if date_range.cover?(time.to_time)
        return true
      end
    end
    return false
  end

end

app/models/seats_reservation.rb
class SeatsReservation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  acts_as_mappable :default_units => :meters,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  belongs_to :restaurant

  has_many :friendships
  has_many :invitations
  has_many :reservations
  has_many :reviews

  before_create :set_role
  before_save :set_full_name

  def admin?
    self.role == "admin"
  end

  def guest?
    self.role == "guest"
  end

  def manager?
    self.role == "manager"
  end

  def restaurant_manager(restaurant)
    self.restaurant_id == restaurant.id
  end

  def friends_rating(restaurant_id)
    ratings = []

    self.friendships.each do |friendship|
      avg_rating = friendship.friend.reviews.where(:restaurant_id => restaurant_id).average(:rating).to_f
      ratings << avg_rating unless avg_rating == 0
    end

    if ratings.count == 0
      return "Not rated yet"
    else
      rating = ratings.sum / ratings.count
      rating.round(2)
    end
  end

  def friend?(guest)
    !self.friendships.where(:user_id => self.id, :friend_id => guest.id).empty?
  end

  def friendship(friend)
    Friendship.where(:user_id => self.id, :friend_id => friend.id).first
  end

  def common_visits(friend)
    if self.reviews || !self.reviews.empty?
      visits = 0
      self.reviews.each do |review|
        if review.reservation.user.id == friend.id
          visits = visits + 1
        else
          visits = visits + review.reservation.invitations.where(:user_id => friend.id, :confirmed => true).count
        end
      end
      return visits
    else
      return "You haven't been anywhere"
    end
  end

  private

  def set_role
    self.role ||= "guest"
  end

  def set_full_name
    if self.first_name && self.last_name
      self.full_name = "#{self.first_name} #{self.last_name}"
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :authenticate_user!, :except => [:index]

  def index
    if current_user
      @invitations = current_user.invitations
    end
  end

end

app/helpers/guests_helper.rb
module GuestsHelper

  def reverse_geocode(guest)
    res = Geokit::Geocoders::GoogleGeocoder.reverse_geocode "#{guest.lat},#{guest.lng}"
    res.full_address
  end

end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_invitations.html.erb
<div class="row"><div class="col-md-6"><h4>Invitations</h4></div></div>
  <% if @invitations.empty? %>
    You don't have any invitations.
  <% else %>
    <% @invitations.each do |invitation| %>

      <% invitation.reservation.expired? %>

        <div class="col-md-4">
          <div class="panel panel-<%= panel_class(invitation) %>">
            <div class="panel panel-heading"><%= invitation.restaurant.title %> restaurant invitation</div>
            <div class="panel panel-body">
              <p>
                Your friend, <b><%= invitation.reservation.user.first_name %></b> has invited you to
                <b><%= invitation.restaurant.title %></b> restaurant.

                When?
                <b><%= l invitation.date, :format => :date_with_time %></b>
                for
                <b><%= invitation.duration %> <%= invitation.duration == 1 ? "hour" : "hours" %>.</b>
                Who else is coming?
                <% invitation.reservation.invitations.each do |invite| %>
                  <% if current_user.id == invite.user_id %>

                    <b><%= invite.reservation.user.first_name %> <%= invite.reservation.user.last_name %> </b> - they invited you

                  <% else %>

                    <b><%= invite.first_name %> <%= invite.last_name %></b>

                  <% end %>
                <% end %>
              </p>

              <% unless invitation.expired? %>
                <% if invitation.confirmed == nil %>
                  <div class="text-center">
                    <%= link_to "Accept", guest_invitation_path(invitation.user_id,
                                                                invitation,
                                                                :invitation => { :confirmed => true }),
                                                                :method => :put,
                                                                :class => "btn btn-primary" %>
                    <%= link_to "Decline", guest_invitation_path(invitation.user_id,
                                                                 invitation,
                                                                 :invitation => { :confirmed => false }),
                                                                 :method => :put,
                                                                 :class => "btn btn-danger" %>
                  </div>
                <% else %>
                  <% if invitation.confirmed %>
                    You have accepted this invitation.
                  <% else %>
                    You have <b>not</b> accepted this invitation.
                  <% end %>
                <% end %>
              <% else %>
                <% if invitation.confirmed %>
                  You have accepted this invitation.
                <% else %>
                  You have <b>not</b> accepted this invitation.
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end%>
    <% end %>
  </div>

app/views/welcome/index.html.erb
  <div class="jumbotron">
    <h1><strong>Welcome to Restaurant Reservations</strong></h1>
  </div>

  <% unless current_user %>
    <div class="col-md-12 text-center">
      <%= form_for(:user, :url => session_path(:user), :class => "form-inline", html: { role: "form" }) do |f| %>
        <div class="form-group">
          <%= f.email_field :email, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
        </div>
        <div class="checkbox">
          <label>
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
          </label>
        </div>
        <%= f.submit 'Sign in', :class => "btn btn-primary" %>
        <%= link_to "Forgot your password?", new_password_path(:user) %>
      <% end %>
    </div>
  <% end %>

  <% if current_user && current_user.guest? %>
    <div class="col-md-12">
      <%= render "invitations" %>
    </div>
  <% end %>

  </br>