config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "welcome#index"

  resources :managers

  resources :guests, :except => [:destroy, :new] do
    resources :invitations, :except => [:edit, :new, :create]
  end

  resources :restaurants do
    resources :configurations, :only => [:create] do
      post :setup_seats
      resources :seats, :only => [:show]
    end

    resources :reservations, :except => [:destroy]

    resources :menus, :except => [:index] do
      resources :meals, :except => [:index]
    end
  end


  resource :users do
    resources :friendships, :except => [:edit, :update, :new]

    resources :reviews, :only => [:index, :show, :update]
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  acts_as_mappable :default_units => :meters,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  has_many :managers, -> { where(:role => "manager") }
  has_one :seats_configuration
  has_many :reviews
  has_one :menu

  validates_presence_of :title

  before_create :tap_configuration
  before_create :tap_menu

  def rating
    Review.all.where(:restaurant_id => self.id).average(:rating).to_f
  end

  private

  def tap_configuration
    self.build_seats_configuration
  end

  def tap_menu
    self.build_menu
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    if params[:sort]
      @restaurants = Restaurant.all.order(params[:sort])
    elsif params[:distance]
      @restaurants = Restaurant.all
      @restaurants.sort_by { |r| r.distance_to(current_user) }
    else
      @restaurants = Restaurant.all
    end
  end

  def show
    @configuration = @restaurant.seats_configuration
    @seats = @configuration.seats
    @date = params[:date]
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_restaurant
    if current_user.manager?
      @restaurant = current_user.restaurant
    else
      @restaurant = Restaurant.find(params[:id])
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:title, :description, :lat, :lng)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

  def seats_check_box(configuration, x, y, time)
    if configuration.seat?(x, y)
      if configuration.seat_reserved?(x, y, time)
        reserved_check_box
      else
        free_check_box(configuration, x, y)
      end
    else
      empty_check_box
    end
  end

  def reserved_check_box
    content_tag(:label, nil, :class => "btn btn-default", :style => "background-color: #B71C1C", :disabled => true) do
      content_tag(:div, :class => "itemcontent configuration-check-box", :disabled => true) do
        check_box_tag(" ", nil, nil, :disabled => true) +
          content_tag(:h5, "")
      end
    end
  end

  def free_check_box(configuration, x, y)
    content_tag(:label, nil, :class => "btn btn-default", :style => "background-color: #00796B") do
      content_tag(:div, :class => "itemcontent configuration-check-box") do
        hidden_field_tag("seat_#{x}_#{y}[x]", x) +
          hidden_field_tag("seat_#{x}_#{y}[y]", y) +
          check_box_tag("seat_#{x}_#{y}[reserved]", true, false) +
          content_tag("span", nil, :class => "fa fa-car fa-2x") +
          content_tag(:h5, "")
      end
    end
  end

  def empty_check_box
    content_tag(:label, nil, :class => "btn btn-default", :disabled => true) do
      content_tag(:div, :class => "itemcontent configuration-check-box") do
        check_box_tag(" ") +
          content_tag(:span, nil, :class => "fa fa-ban fa-2x") +
          content_tag(:h5, "")
      end
    end
  end

end

app/views/restaurants/_choose_date.html.erb
<div class="col-md-6">
  <%= form_tag(restaurant_path(@restaurant), :method => :get, :class => "form-inline") do %>

    <%= label_tag :date, "Choose a date for your reservation" %>

        <% if params[:date] && params[:duration] %>
          <div class="form-group">
            <%= text_field_tag :date,
                               params[:date],
                               :class => "form-control",
                               :disabled => true %>
          </div>
          <p>
          <div class="form-group">
            <%= label_tag :duration, "How long would you like to stay?" %>
            <%= text_field_tag :duration,
                               params[:duration],
                               :class => "form-control",
                               :disabled => true %>
          </div>
        <% else %>
          <div class='input-group date' id='datetimepicker1'>
            <%= text_field_tag :date,
                               params[:date],
                               :class => "form-control" %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
          <p>
          <div class="form-group">
            <%= label_tag :duration, "How long would you like to stay?" %>
            <%= select_tag :duration, "<option>1 hour</option>
                                      <option>2 hours</option>
                                      <option>3 hours</option>
                                      <option>4 hours</option>
                                      <option>5 hours</option>
                                      <option>6 hours</option>".html_safe,
                                      :class => "form-control" %>
          </div>
       <% end %>

    <%= submit_tag "Show", :class => "form-control" %></br>
  <% end %>
</div>
<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel panel-heading">Instructions</div>
    <div class="panel panel-body">
      <div class="row" style="margin: -5px">
        <div data-toggle="buttons" class="btn-group itemcontent">
          <%= empty_check_box %> - Empty space
        </div>
        <div data-toggle="buttons" class="btn-group itemcontent">
          <%= reserved_check_box %> - Reserved table
        </div>
        <div data-toggle="buttons" class="btn-group itemcontent">
          <%= free_check_box(1, 1, 1) %> - Free table (clickable)
        </div>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/_configuration_set_up.html.erb
<% if current_user.manager? %>
  <%= form_tag restaurant_configuration_setup_seats_path(@restaurant, @configuration) do %>
    <table>
      <tbody>
      <% @configuration.height.times do |rows| %>
        <tr>
          <% @configuration.width.times do |cols| %>
            <%= hidden_field_tag("seat_#{rows}_#{cols}[x]", rows) %>
            <%= hidden_field_tag("seat_#{rows}_#{cols}[y]", cols) %>
            <td><%= check_box_tag("seat_#{rows}_#{cols}[reserved]", true, false,
                                  :class => "configuration-check-box") %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= submit_tag "Setup configuration", :class => "btn btn-primary" %>
  <% end %>
<% else %>
  <h4>Sorry, this restaurant configuration is not set up yet. Please check later.</h4>
<% end %>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :lat, "Address Latitude" %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng, "Address Longitude" %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_managers.html.erb
<% if @restaurant.managers.present? %>
  <div class="panel panel-default">
    <div class="panel panel-heading">Managers</div>
    <div class="panel panel-body">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>First name</th>
              <th>Last name</th>
              <th>Phone number</th>
              <th>Address</th>
              <th>Email</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @restaurant.managers.each do |manager| %>
              <tr>
                <td><%= manager.first_name %>
                <td><%= manager.last_name %>
                <td><%= manager.phone_number %>
                <td><%= manager.address %>
                <td><%= manager.email %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/restaurants/_menu.html.erb
<div class="panel panel-info">
  <div class="panel panel-heading"><%= @restaurant.menu.title ? @restaurant.menu.title : "Menu" %></div>
  <div class="panel panel-body">
    <% if @restaurant.menu.meals.empty? %>
      There is nothing on the menu.
    <% else %>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th>Price</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @restaurant.menu.meals.each do |meal| %>
              <tr>
                <td><%= meal.title %></td>
                <td><%= meal.description %></td>
                <td><%= meal.price %></td>
                <td><%= link_to 'Show', restaurant_menu_meal_path(@restaurant, @restaurant.menu, meal) %></td>
                <% if current_user.restaurant_manager(@restaurant) %>
                  <td><%= link_to 'Edit', edit_restaurant_menu_meal_path(@restaurant, @restaurant.menu, meal) %></td>
                  <td><%= link_to 'Destroy', restaurant_menu_meal_path(@restaurant, @restaurant.menu, meal), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
  <% if current_user.restaurant_manager(@restaurant) %>
    <div class="panel panel-footer text-center">
      <%= link_to "Add meals", new_restaurant_menu_meal_path(@restaurant, @restaurant.menu),
                  :class => "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/restaurants/_reserve_tables.html.erb
<% if params[:date] && params[:duration] %>
  <%= form_tag restaurant_reservations_path(@restaurant) do %>
    <div class="col-md-6">
      <table>

        <tbody>
        <% cache([@configuration, @seats]) do %>
          <% @configuration.height.times do |rows| %>
            <tr>
              <% @configuration.width.times do |cols| %>
                <td>
                <div data-toggle="buttons" class="btn-group itemcontent">
                  <%= seats_check_box(@configuration, rows, cols, @date || Time.now) %>
                </div>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
        </tbody>

      </table>
    </div>

    <div class="col-md-6"></div>
    <div class="col-md-6">
      <% if current_user.guest? %>
        <div class="panel panel-default">
          <div class="panel panel-heading">Invite a friend to a restaurant</div>
          <div class="panel panel-body">
            <div class="table-responsive">
              <% if current_user.friendships.count == 0 %>
                Seems like you don't have any friends. Go to your profile to add some.
              <% else %>
                <table class="table">
                  <thead>
                    <tr>
                      <th>First name</th>
                      <th>Last name</th>
                      <th>Email</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>

                  <tbody>
                  <% current_user.friendships.each do |friendship| %>
                    <tr>
                      <td><%= friendship.friend.first_name %>
                      <td><%= friendship.friend.last_name %>
                      <td><%= friendship.friend.email %>
                      <%= hidden_field_tag("friendship_#{friendship.id}[friend_id]", friendship.friend_id) %>
                      <td><%= check_box_tag("friendship_#{friendship.id}[selected]", true, false) %></td>
                    </tr>
                  <% end %>
                </table>
              <% end %>
            </div>
          </div>

          <%= hidden_field_tag("reservation[date]", params[:date]) %>
          <%= hidden_field_tag("reservation[duration]", params[:duration]) %>

          <div class="panel panel-footer text-center">
            <%= submit_tag "Make a reservation", :class => "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  <% end %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing Restaurants</h1>

<%= link_to "Sort by title",
            restaurants_path(:sort => "title"),
            :class => "btn btn-info" %>
<%= link_to "Sort by description",
            restaurants_path(:sort => "description"),
            :class => "btn btn-info" %>
<%= link_to "Sort by distance",
            restaurants_path(:distance => "distance"),
            :class => "btn btn-info" %>
<%= link_to "Unsort",
            restaurants_path,
            :class => "btn btn-info" %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Distance (m)</th>
        <th>Rating</th>
        <% if current_user.guest? %>
          <th>Friends rating</th>
        <% end %>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td><%= restaurant.title %></td>
          <td><%= restaurant.description %></td>
          <td><%= restaurant.distance_from(current_user, :units => :meters).round(2) %></td>
          <td><%= restaurant.rating == 0 ? "Not rated yet" : restaurant.rating.round(2) %>
          <% if current_user.guest? %>
            <td><%= current_user.friends_rating(restaurant.id) %>
          <% end %>
          <td><%= link_to 'Reservation', restaurant %></td>
          <td><%= link_to 'Your reservations', restaurant_reservations_path(restaurant) if current_user.guest? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant) if current_user.restaurant_manager(restaurant) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Restaurant', new_restaurant_path if current_user.admin? %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="jumbotron restaurant">
  <h1><strong><%= @restaurant.title %></strong></h1>
  <p>
    <%= @restaurant.description %>
  </p>
</div>

<% if @seats.present? %>
  <%= render "choose_date" %>

  <div class="col-md-12">
    <%= render "reserve_tables" %>
  </div>

<% else %>

  <%= render "configuration_set_up" %>

<% end %>

<div class="col-md-12"><br></div>

<div class="col-md-12">

  <%= render "menu" %>

</div>

<div class="col-md-12 text-center">
  <div class="panel panel-default">
    <div class="panel panel-body">

      <div style='width: 800px;' class="text-center">
        <div id="map" style='width: 800px; height: 400px;'></div>
      </div>

    </div>
  </div>
</div>

<div class="col-md-12"><br></div>

<div class="col-md-12">

  <%= render "managers" %>

  <div class="text-center">
  <% if current_user.restaurant_manager(@restaurant) %>
    <%= link_to 'Edit', edit_restaurant_path(@restaurant), :class => "btn btn-primary" %> |
    <%= link_to 'Edit menu', edit_restaurant_menu_path(@restaurant, @restaurant.menu), :class => "btn btn-primary" %> |
  <% end %>
  <%= link_to 'Back', restaurants_path, :class => "btn btn-info" %><br>
  </div>
</div>

<div class="col-md-12"><br></div>

<script>
  var directionsDisplay = new google.maps.DirectionsRenderer();
  var directionsService = new google.maps.DirectionsService();

  function calcRoute() {
    var origin      = new google.maps.LatLng(<%= current_user.lat %>, <%= current_user.lng %>);
    var destination = new google.maps.LatLng(<%= @restaurant.lat %>,<%= @restaurant.lng %>);
    var request = {
        origin:      origin,
        destination: destination,
        travelMode:  google.maps.TravelMode.DRIVING
    };
    directionsService.route(request, function(response, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
      }
    });
  }

  calcRoute();

  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'map'}}, function(){
    directionsDisplay.setMap(handler.getMap());
  });
</script>