config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "welcome#index"

  resources :managers

  resources :guests, :except => [:destroy, :new] do
    resources :invitations, :except => [:edit, :new, :create]
  end

  resources :restaurants do
    resources :configurations, :only => [:create] do
      post :setup_seats
      resources :seats, :only => [:show]
    end

    resources :reservations, :except => [:destroy]

    resources :menus, :except => [:index] do
      resources :meals, :except => [:index]
    end
  end


  resource :users do
    resources :friendships, :except => [:edit, :update, :new]

    resources :reviews, :only => [:index, :show, :update]
  end
end

app/models/admin.rb
class Admin < User
  before_create :set_role

  default_scope { where(:role => "admin") }

  private

  def set_role
    self.role ||= "admin"
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  belongs_to :guest, :foreign_key => :user_id

  validates_presence_of :user_id
  validates_presence_of :friend_id

  def friend
    Guest.find(self.friend_id)
  end

end

app/models/guest.rb
class Guest < User
  before_create :set_role

  default_scope { where(:role => "guest") }

  private

  def set_role
    self.role ||= "guest"
  end

  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ? OR full_name ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base

  belongs_to :user, -> { where(:role => "guest") }
  belongs_to :reservation

  has_one :review, :dependent => :destroy

  delegate :date, :to => :reservation
  delegate :duration, :to => :reservation
  delegate :restaurant, :to => :reservation

  delegate :first_name, :to => :user
  delegate :last_name, :to => :user

  def expired?
    date_range = self.date.localtime..self.date.localtime + self.duration.hours

    unless date_range.cover?(Time.now)
      unless self.review.present?
        if self.confirmed
          self.create_review!(:restaurant_id => self.restaurant.id,
                              :user_id => self.user.id)
        end
      end
    end

    !date_range.cover?(Time.now)
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_mappable :default_units => :kilometers,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
end

app/models/manager.rb
class Manager < User
  before_create :set_role

  default_scope { where(:role => "manager") }

  private

  def set_role
    self.role ||= "manager"
  end
end

app/models/meal.rb
class Meal < ActiveRecord::Base

  belongs_to :menu

  validates_presence_of :title
  validates_presence_of :price

end

app/models/menu.rb
class Menu < ActiveRecord::Base

  belongs_to :restaurant

  has_many :meals

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  has_and_belongs_to_many :seats
  has_many :invitations
  has_one :review

  belongs_to :restaurant
  belongs_to :user

  validates_presence_of :date
  validates_presence_of :duration

  delegate :title, :to => :restaurant

  def expired?
    date_range = self.date.localtime..self.date.localtime + self.duration.hours

    unless date_range.cover?(Time.now)
      unless self.review.present?
        self.create_review!(:restaurant_id => self.restaurant.id,
                            :user_id => self.user.id)
      end
    end

    !date_range.cover?(Time.now)
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  acts_as_mappable :default_units => :meters,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  has_many :managers, -> { where(:role => "manager") }
  has_one :seats_configuration
  has_many :reviews
  has_one :menu

  validates_presence_of :title

  before_create :tap_configuration
  before_create :tap_menu

  def rating
    Review.all.where(:restaurant_id => self.id).average(:rating).to_f
  end

  private

  def tap_configuration
    self.build_seats_configuration
  end

  def tap_menu
    self.build_menu
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :restaurant
  belongs_to :invitation
  belongs_to :reservation

  def reservation
    self[:reservation_id] ? Reservation.find(self[:reservation_id]) : self.invitation.reservation
  end

end

app/models/seat.rb
class Seat < ActiveRecord::Base

  belongs_to :seat_configuration

  has_and_belongs_to_many :reservations

  def reserved?(time)
    return false if self.reservations.empty?

    self.reservations.each do |reservation|
      date_range = reservation.date.localtime..reservation.date.localtime + reservation.duration.hours
      if date_range.cover?(time.to_time)
        return true
      end
    end
    return false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  acts_as_mappable :default_units => :meters,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  belongs_to :restaurant

  has_many :friendships
  has_many :invitations
  has_many :reservations
  has_many :reviews

  before_create :set_role
  before_save :set_full_name

  def admin?
    self.role == "admin"
  end

  def guest?
    self.role == "guest"
  end

  def manager?
    self.role == "manager"
  end

  def restaurant_manager(restaurant)
    self.restaurant_id == restaurant.id
  end

  def friends_rating(restaurant_id)
    ratings = []

    self.friendships.each do |friendship|
      avg_rating = friendship.friend.reviews.where(:restaurant_id => restaurant_id).average(:rating).to_f
      ratings << avg_rating unless avg_rating == 0
    end

    if ratings.count == 0
      return "Not rated yet"
    else
      rating = ratings.sum / ratings.count
      rating.round(2)
    end
  end

  def friend?(guest)
    !self.friendships.where(:user_id => self.id, :friend_id => guest.id).empty?
  end

  def friendship(friend)
    Friendship.where(:user_id => self.id, :friend_id => friend.id).first
  end

  def common_visits(friend)
    if self.reviews || !self.reviews.empty?
      visits = 0
      self.reviews.each do |review|
        if review.reservation.user.id == friend.id
          visits = visits + 1
        else
          visits = visits + review.reservation.invitations.where(:user_id => friend.id, :confirmed => true).count
        end
      end
      return visits
    else
      return "You haven't been anywhere"
    end
  end

  private

  def set_role
    self.role ||= "guest"
  end

  def set_full_name
    if self.first_name && self.last_name
      self.full_name = "#{self.first_name} #{self.last_name}"
    end
  end

end

app/helpers/guests_helper.rb
module GuestsHelper

  def reverse_geocode(guest)
    res = Geokit::Geocoders::GoogleGeocoder.reverse_geocode "#{guest.lat},#{guest.lng}"
    res.full_address
  end

end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
 <%= nav_bar :fixed => :bottom, :responsive => :true, :id => "footer" do %>
  <p class="navbar-text pull-left">Made by nikolalsvk
  </p>
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit password', edit_user_registration_path, :class => 'navbar-link' %> |
    <% if current_user.guest? %>
      <%= link_to 'Edit profile', edit_guest_path(User.find(current_user.id)), :class => 'navbar-link' if current_user.guest? %> |
    <% end %>
    <% if current_user.manager? %>
      <%= link_to 'Edit profile', edit_manager_path(Manager.find(current_user.id)), :class => 'navbar-link' if current_user.manager? %> |
    <% end %>
    <%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Sign in", new_user_session_path, :class => 'navbar-link' %>
  <% end %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<%= nav_bar static: :top, :responsive => true do %>
  <%= menu_group :pull => :left do %>
    <%= menu_item "Home", root_path %>
    <%= menu_item "Restaurants", restaurants_path %>
    <%= menu_item "Friends", users_friendships_path if current_user && current_user.guest? %>
    <%= menu_item "Managers", managers_path if current_user && current_user.admin? %>
    <%= menu_item "Visits", users_reviews_path if current_user && current_user.guest? %>
    <%= menu_item "Invitations", guest_invitations_path(current_user) if current_user && current_user.guest? %>
  <% end %>
  <%= menu_group :pull => :right do %>

    <% if current_user %>
      <%= menu_item "Add manager", new_manager_path if current_user.admin? %>
      <%= menu_item "My profile", guest_path(current_user) if current_user.guest? %>
    <% end %>

  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantReservation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrap">

  <div class="container">
    <% if notice %>
      <p class="alert alert-success" id="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger" id="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

    <div class="col-md-12 text-center"><br></div>
    <div class="col-md-12 text-center"><br></div>
    <div class="col-md-12 text-center"><br></div>
  </div>


  <div class="push"></div>
</div>

<%= render "layouts/footer" %>

</body>
</html>